jazzband/geojson

- README.rst
- geojson/feature.py
- tests/test_geo_interface.py
The GeoJSON specification (https://tools.ietf.org/html/draft-butler-geojson-05#section-2.2) states that:
> If a feature has a commonly used identifier, that identifier SHOULD be included as a member of the feature object with the name "id" and the value of this member is either a JSON string or number.
At the moment python-geojson adds id: null for every feature, unless specified. This is very problematic especially on geojson.io web service, which breaks when such features are present (https://github.com/mapbox/geojson.io/issues/450).
This is a PR to fix this behaviour.
> Do not add id: null for Features

- README.rst
- geojson/__init__.py
- geojson/validation.py
- tests/test_validation.py
Hi!
I notice what allows to construct object even if is not valid by specification and i created module for checking validation for objects. Now is something like a "concept"(or very restricted version), because i don't know about needs this for you. No tests and no documentation, but contains two objects ```LineString``` and ```MultiLineString```. How it works:
```python
>>> from geojson import LineString, MultiLineString, IsValid
>>> IsValid(LineString([(8.919, 44.4074), (8.923, 44.4075)]))
{'valid': 'yes', 'message': ''}
>>> IsValid(LineString([(8.919, 44.4074)]))
{'valid': 'no', 'message': 'the "coordinates" member must be an array of two or more positions'}
>>> IsValid(MultiLineString([[(10,5), (4,3)]]))
{'message': '', 'valid': 'yes'}
>>> IsValid(MultiLineString([[(10,5)]])) …
```
> add validation for geojson objects

- geojson/utils.py
Hi @frewsxcv 
As suggested here is a pull request for work initial work on generating random data. 
Cheers
Rowan
> Initial commit of generating random data

- geojson/validation.py
- tests/test_validation.py
This pull-request fix the multipolygon validation (and the associated test).
Tha data used for testing were false.
> Fix MultiPolygon validation

- geojson/utils.py
It's unclear to me that the map_coords function only results in applying a function to the individual dimensions of the tuple. This works well for basic scalling, but if you scale arbitrarily, you lose a lot of the 'geo' part of json, which is the geometric center issue.
I've also added a worked example of transforming coords in another pull request with the same scaffold of list comprehension.
> Clarified map_coords

- geojson/geometry.py
- tests/test_validation.py
What would you think about adding a `validate` parameter to the `Geometry` constructor?
If I was starting this library from scratch, I would make this an opt-out (i.e. I would make it `True` by default), but I guess now it would be a breaking change...
> Add validate parameter

- setup.py
> Remove runtime dependency on setuptools

- geojson/geometry.py
- tests/test_validation.py
> Errors method for validating geometry collections.

- README.rst
- geojson/utils.py
Fix tests to make https://github.com/frewsxcv/python-geojson/pull/109 mergeable.
> Fix PR #109.

- geojson/geometry.py
This change includes the correct docstring for use with both Point and MultiPoint geometry.
Fixes #113
> Fix type hinting for MultiPoint geometry

- .travis.yml
- CHANGELOG.rst
- README.rst
- geojson/_version.py
- setup.py
- tox.ini
- Tie Travis CI to jazzband instance
- Remove EOL 3.3 and 3.4 version support
- Add 3.7 version support
The broken URL "details" link for the Travis CI build on https://github.com/jazzband/python-geojson/pull/119 led me to discover these issues.
> Fix up Travis CI and Python version support

- README.rst
- tests/test_base.py
- tests/test_constructor.py
- tests/test_geo_interface.py
- change occurences of deprecated `AssertEquals()` to preferred `AssertEqual()`
> fix unittest deprecation warnings

- geojson/utils.py
- tests/test_coords.py
I noticed that a Feature passed to `geojson.utils.map_tuples()` loses it's ID. Here is a [simple replication](https://repl.it/@bryik/python-geojson-lib-maptuple-removes-IDs).
The cause seems to be that IDs are [not included in the dict returned by geojson.utils.map_geometry()](https://github.com/jazzband/python-geojson/blob/master/geojson/utils.py#L123).
**This PR:**
- adds the ID to the dict aca22cb
- adds a test to check ID is present after mapping f3e876a
> Fix map_geometries() loss of feature IDs

- geojson/utils.py
- tests/test_coords.py
Following up on #128
See also #110
> Streamline support for Feature objects in coord mapping utils

- README.rst
- geojson/geometry.py
- tests/test_coords.py
- tests/test_features.py
- tests/test_geo_interface.py
> Add default lat/lon precision to base Geometry class

- docs/index.rst
This PR uses a reST include directive in attempts of facilitating autogenerated ReadTheDocs docs while maintaining the rendered README on the GitHub repo homepage.
> Add include directive for Sphinx docs

- geojson/geometry.py
- tests/test_validation.py
When you initialize a point using coordinates for a line, it says is a valid point:
```
import geojson
lineCoords=[[1,2],[3,4]]
pointCoords=[5,6]
print ("Line(lineCoords): ", geojson.LineString(lineCoords).is_valid)
print ("Line(pointCoors): ", geojson.LineString(pointCoords).is_valid)
print ("Point(pointCoords): ", geojson.Point(pointCoords).is_valid)
print ("Point(lineCoords): ", geojson.Point(lineCoords).is_valid)
```
Which produces the next exit:
> Line(lineCoords):  True
> Line(pointCoors):  False
> Point(pointCoords):  True
> Point(lineCoords):  True
The reason behind this, is because the position array is only validating it's length, but not the format.
I think this pull request solves the problem
> Improve point validation

- geojson/utils.py
- tests/test_utils.py
The polygon generation did not respect the given bounding box. The PR includes unittests for that issue and a small fix.
> Fix polygon generation

- setup.py
Follow-up to https://github.com/jazzband/geojson/pull/148 to get the intended effect of supporting only Python 3.6, 3.7, and 3.8
> Proper check for supported Python version

- tests/test_features.py
> Remove encoding parameter from json.load for Python 3.9 compatibility.

- tox.ini
This tiny update will allow `tox` to test only the currently supported Python versions.
> Update tox config to drop Python 2.7 support

- .github/workflows/test.yml
- README.rst
- geojson/base.py
- geojson/examples.py
- geojson/feature.py
- geojson/geometry.py
- geojson/mapping.py
- geojson/utils.py
- setup.py
- tests/test_base.py
- tests/test_constructor.py
- tests/test_coords.py
- tests/test_features.py
- tests/test_geo_interface.py
- tests/test_validation.py
- tox.ini
Adds testing and the Trove classifier for Python 3.9, which came out last month.
Also upgrades Python syntax with https://github.com/asottile/pyupgrade `--py36-plus` and removes some redundant Python 2 code.
This also adds:
```python
python_requires=">=3.6, <=3.9",
```
Which helps pip only install for those versions, so perhaps this could be removed from `setup.py`?
```python
if not (major_version == 3 and 6 <= minor_version <= 9):
sys.stderr.write("Sorry, only Python 3.6 - 3.9 are "
"supported at this time.\n")
exit(1)
```
I'd also suggest removing the upper limit too; when Python 3.10 comes out next October, it'll _probably_ work, and people won't need to wait for a new release of geojson.
> Add support for Python 3.9

- geojson/codec.py
> Add utf-8 support to geojson.dumps

- README.rst
- geojson/geometry.py
Authored by @rogerlew , with their permission I am submitting as a pull request.
Resolves #135 
This allows projects to set the default precision that they need, in such a way that it works with `geojson.base.GeoJSON.to_instance` (i.e. when parsing a large JSON tree of objects using factories, without calling individual constructors.)
IQGeo is submitting this pull request because we are unable to upgrade beyond 2.4 without this fix.
> geometry module level default precision control

- README.rst
The original polygon does not respect the geojson convention (2016) for point windings --> right hand rule. 
I did not check other geometries though. 
Best regards,
> Update README - point winding convention

- geojson/geometry.py
Changes made per discussion in #173. Suggestions were made to handle all real numbers as inputs, rather than the original `float, int, Decimal` types only. While the original type-check works for a majority of cases, there are users who may try to create geojson objects from objects that are not inherited from the python base-classes listed above. A more generic solution was to type-check against the abstract `Numbers` class, which has a nicely laid out hierarchy per PEP 3141.
> Change made to handle all real numbers as coordinates #173

- CHANGELOG.rst
- geojson/_version.py
3.0.0 (2022-01-26)
------------------
- Support for Python versions 3.7-3.11 (Python 2 no longer supported)
- Primary development branch renamed from `master` to `main`
- Handle all real numbers as coordinates
- https://github.com/jazzband/geojson/pull/188
- Default precision improvements
- https://github.com/jazzband/geojson/pull/177
- CI improvements
- https://github.com/jazzband/geojson/pull/172
- https://github.com/jazzband/geojson/pull/155
- utf-8 support added to `geojson.dumps()`
- https://github.com/jazzband/geojson/pull/165
- Polygons now constrained to bounding box
- https://github.com/jazzband/geojson/pull/147
- Better GeometryCollection handling in `util.coords()`
- https://github.com/jazzband/geojson/pull/146
- Improved point validation
- …
> Version 3.0.0

- .github/workflows/release.yml
- .github/workflows/test.yml
Fixes a deprecation warning at https://github.com/jazzband/geojson/actions/runs/4012584880
> [> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1](https://github.com/jazzband/geojson/commit/60813ae6aa8206038a3ccb27f3f62fcaa25d9230#annotation_8286510014)
You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
Docs: …
> Update action's branch to fix deprecation warning

- setup.cfg
While preparing to release GeoJSON 3.0.0 it became apparent that a Python-2-compatible wheel was still being generated by the CI release tool. This removes the config that caused that behavior.
> Stop building universal wheel because Python 2 is no longer supported

- setup.py
The upper bound in python_requires "<=3.11" excludes patch versions of Python 3.11, as, e.g., Python 3.11.1.
> ERROR: Package 'geojson' requires a different Python: 3.11.1 not in '<=3.11,>=3.7'
By switching from an inclusive to an exclusive upper bound of 3.12, geojson can now be used with all Python 3.11 versions.
> setup.py: Allow Python 3.11 patch versions

- CHANGELOG.rst
According to the commit history and git tags, version 3.0.0 and 3.0.1 were released in 2023.
> Fix date of changelog for 3.0.0 and 3.0.1

- .github/workflows/test.yml
> Update python package name from codecov to coverage

- .github/workflows/test.yml
- setup.py
- tox.ini
Python 3.12 will be in beta in May, which is when third-party projects should start testing it in advance of the October release.
The reason for this is three-fold:
* Find 3.12 incompatibilities in this library and fix them in time
* Find bugs in Python itself, to report them upstream and fix them for everyone
* Allow other libraries that depend on this one, to install and test 3.12
> Test Python 3.12-dev

- .github/workflows/test.yml
- .gitignore
- .pre-commit-config.yaml
- README.rst
- setup.py
- tests/data.geojson
- tox.ini
The merge of https://github.com/jazzband/geojson/pull/211 failed the CI for Python 3.12:
https://github.com/jazzband/geojson/actions/runs/5098872321/jobs/9166263747
```
Run coverage run --branch --source=geojson setup.py test
Traceback (most recent call last):
File "/home/runner/work/geojson/geojson/setup.py", line 1, in <module>
from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
```
That's because the 3.12 beta removed setuptools from Python. We could install setuptools on the CI, but really we shouldn't be running tests via `python setup.py test` - we shouldn't invoke `setup.py` directly. See https://blog.ganssle.io/tag/setuptools.html for the long version.
Instead, let's modernise testing and use pytest and tox to run the tests.
So for example, tests can be …
> Fix tests and don't invoke setup.py directly

- .flake8
- .github/workflows/lint.yml
- .pre-commit-config.yaml
- geojson/utils.py
Summary:
- Fix flake8 errors
```
$ flake8 .
geojson/codec.py:30:80: E501 line too long (82 > 79 characters)
geojson/codec.py:32:80: E501 line too long (88 > 79 characters)
geojson/geometry.py:15:80: E501 line too long (82 > 79 characters)
geojson/utils.py:212:11: E275 missing whitespace after keyword
geojson/utils.py:214:13: E275 missing whitespace after keyword
geojson/utils.py:216:13: E275 missing whitespace after keyword
```
- Setup CI job for flake8
> Setup flake8 CI job

- .gitignore
- CHANGELOG.rst
- README.rst
- setup.py
Dear @frewsxcv, @rayrrr, and @hugovk,
thanks a stack for conceiving and maintaining the geojson package.
Currently, it is apparently not possible to install the package on Python 3.12 without further ado, see our report at GH-221. This patch intends to improve the situation.
With kind regards,
Andreas.
> Add support for Python 3.12

- geojson/base.py
- geojson/codec.py
- geojson/geometry.py
- geojson/utils.py
- tests/__init__.py
- tests/test_utils.py
1. Use f-strings
2. Use integers where appropriate
3. Refactor generate_random
> Modernize code

- geojson/utils.py
- tests/test_utils.py
Follow up to #218. From [RFC 7946 Section 3.1.1](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1) (emphasis added):
> A position is an array of numbers.  There MUST be two or more
elements.  The first two elements are longitude and latitude, or
easting and northing, precisely in that order and using _decimal_
numbers.
> restore floats (as per RFC 7946 Section 3.1.1)

- .github/workflows/test.yml
- README.rst
- setup.py
- tox.ini
As reported in [Debian Bug #1082218](https://bugs.debian.org/1082218), `setup.py` fails with Python 3.13.
This is fixed by bumping the upper bound, as the Debian package built fine with 3.13rc2.
> Don't fail with Python 3.13.
